services:
  postgres:
    image: postgres:17
    container_name: url-shortener-postgres
    environment:
      POSTGRES_DB: url_shortener
      POSTGRES_USER: satyamsingh
      POSTGRES_PASSWORD: password

  redis:
    image: redis:8

  app:
    build: .
    container_name: url-shortener-api
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis